name: Publishing

on:
  push:
    branches:
      - master

jobs:

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/achallonge-compat-fork
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v3
    - name: Publishing package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
